### ISSUE TITLE
Pr.2: La forma de tipar las funciones es confuso

### ISSUE THREAD

**Issue by DiegoMoronha** [AFernandoDan/EstrD2023s1#12]
Al escribir funciones de haskell lo mejor es evitar usar el _ sobre todo al finalizar la funcion ya que puede generar confusion tanto para la correccion como tambien puede generar errores al compilar, por ej : si sin querer pones un espacio entre el nombre y el _ podes hacerle creer al compilador que es un argumento que no te interesa

**Comment by AFernandoDan** [comment]
En este caso algunas funciones las deje con guiones bajos porque así venia en la práctica, pero ya lo solucioné.

**Comment by AFernandoDan** [comment]
Resuelto
