### ISSUE TITLE
Pr.2: en cuentaRegresiva no tenés en cuenta los valores negativos

### ISSUE THREAD

**Issue by DiegoMoronha** [AFernandoDan/EstrD2023s1#13]
El enunciado pide explícitamente que se contemplen, pues establece que NO debe ser un error. Así como está definida, los números negativos se cuelgan.

**Comment by AFernandoDan** [comment]
Resuelto

**Comment by DiegoMoronha** [comment]
Estas tomando un caso de mas , ya que n<1 ya considera el caso base de 0

**Comment by AFernandoDan** [comment]
Si en ese sentido me pareció extraño como me quedo ya que tanto para 0 como cualquier x < 1 el resultado es el mismo [].

**Comment by AFernandoDan** [comment]
Resuelto

**Comment by DiegoMoronha** [comment]
Estaba bien como estaba , lo que te decía es que el caso base de 0 no es necesario solo con el caso en el if era suficiente

O sea cuentaRegresiva 0 = [ ] este estaba de más el ejercicio estaba correcto con 1 ya que si era menor que 1 es porque era 0 o menos y daba []

**Comment by AFernandoDan** [comment]
Entiendo, ahora si me quedo claro. Lo que veo es que en este caso no es 100% recursión estructural. Al intentar forzarlo puse un caso demas.

**Comment by DiegoMoronha** [comment]
En realidad si es recursión estructural pero no hace falta plantear ese caso como PM, para la recursión estructural tenés que tener un caso base (lo que está en el then) y un caso inductivo que debes usar para resolver el ejercicio (hecho en el else) .
En si es recursión estructural pero no cumple exactamente el esquema que se plantea por PM. Dicho esto cierro el issue .buen trabajo :)
