### ISSUE TITLE
Pr.3: La funcion ponerN no respeta el esquema de RE

### ISSUE THREAD

**Issue by DiegoMoronha** [AFernandoDan/EstrD2023s1#16]
Si bien la idea esta buena y es por ahi no estas haciendo el esquema de RE , estas poniendo una bolita en el caso inductivo de la recursion y no en la recursion en si

**Comment by AFernandoDan** [comment]
No entiendo, ¿Podrías ser más específico?.

**Comment by DiegoMoronha** [comment]
Claro

Vos tenés esto:

ponerN  ::  Int  ->  Color  ->  Celda  ->  Celda
ponerN 0 c cel = cel
ponerN n c cel = ponerN (n - 1 ) c (poner c cel)

El esquema de RE planteado se ve así
ponerN  ::  Int  ->  Color  ->  Celda  ->  Celda
ponerN 0 c cel = ....
ponerN n c cel = ....... ponerN( n-1) c cel

Vos no tenes que poner en "cel" sino en la recursión

**Comment by AFernandoDan** [comment]
Perfecto, ya entendí. Ahora lo corrijo. Una última duda ¿Ya corregiste toda mi practica 3?, pregunto esto porque se me hizo raro ver solo un issue.

**Comment by AFernandoDan** [comment]
Resuelto

**Comment by DiegoMoronha** [comment]
Perfecto, muy buen trabajo , si la práctica está revisada ,si veo algún detalle creo algún issue pero está bastante bien todo :)
