### ISSUE TITLE
Pr.1: La función vieneDespues es incorrecta

### ISSUE THREAD

**Issue by DiegoMoronha** [AFernandoDan/EstrD2023s1#3]
La función vieneDespues definida no es la pedida. Por ejemplo, Miercoles viene después que Lunes, pero tu función no lo indica adecuadamente, porque solamente considera el caso inmediato siguiente, y no todos.
Atención al corregirla de no caer en una explosión combinatoria de casos. El consejo es usar subtareas adecuadas.

**Comment by AFernandoDan** [comment]
Resuelto
